### ISSUE TITLE
ClassCastException issue

### ISSUE THREAD

**Issue by emlathotrang121** [minhlong293/thrift_client_pool#2]
Please help me. Somehow I got this issue: ;((

```
Exception in thread "Thread-1" java.lang.ClassCastException: org.apache.thrift.TApplicationException cannot be cast to org.apache.thrift.transport.TTransportException
	at com.github.minhlong293.thrift.common.ThriftExceptionHelper.isDisconnectedException(ThriftExceptionHelper.java:31)
	at com.github.minhlong293.thrift.clientwrapper.ClientWrapper$ClientInvocationHandler.checkTException(ClientWrapper.java:107)
	at com.github.minhlong293.thrift.clientwrapper.ClientWrapper$ClientInvocationHandler.invoke(ClientWrapper.java:120)
	at com.sun.proxy.$Proxy2.getSqrt(Unknown Source)
```
--- from HML fan club ---

**Comment by azlyfan** [comment]
I accidentally have the same issue. It seems that all Thrift Exceptions are cast into TTransportException for some reasons. I have recently used this library which is highly recommended by one of my friend, a Vietnamese one so I am pretty shocked after figuring this careless type casting. I definitely expected something better.

**Comment by quangvd917** [comment]
I think the "some reasons" mentioned by @azlyfan is "checking connection status". It would be an awesome feature if implemented better and it might need more unit testing btw

**Comment by minhlong293** [comment]
@azlyfan @emlathotrang121 @quangvd917 
It's a my mistake, instead of check the exception is instance of TTransportException, I was check it is TException.

You can check the update here:
https://github.com/minhlong293/thrift_client_pool/blob/master/src/main/java/com/github/minhlong293/thrift/common/ThriftExceptionHelper.java
```
public static boolean isDisconnectedException(Exception e) {
        if (e instanceof TTransportException) { //here is my mistake, TException -> TTransportException 
            TTransportException te = (TTransportException) e;
            if (THRIFT_EXCEPTION_CAUSE_DISCONNECTED.contains(te.getType())) {
                return true;
            }
        }
        return false;
    }
```

I added a test here:
https://github.com/minhlong293/thrift_client_pool/blob/test/src/test/java/com/github/minhlong293/thrift/common/ThriftExceptionHelperTest.java

You can use the newest version to avoid this issue:

> //for thrift ver 0.9.3
> dependencies {
>     compile group: 'com.github.minhlong293', name: 'clientpool', version: '0.9.3-2'
> }
> //for thrift ver 0.11.0
> dependencies {
>     compile group: 'com.github.minhlong293', name: 'clientpool', version: '0.11.0-2'
> }

Best Regards.
